create table daily_reports (
    id                              bigint generated by default as identity primary key,
    report_date                     date          not null unique,
    facilities_active_count         integer       not null,
    new_permits_issued_count        integer       not null,
    permits_expiring_soon_count     integer       not null,
    inspections_completed_count     integer       not null,
    inspections_passed_count        integer       not null,
    inspections_failed_count        integer       not null,
    compliance_rate_pct             decimal(5,1)  not null
);

insert into daily_reports (
    report_date, facilities_active_count, new_permits_issued_count, permits_expiring_soon_count,
    inspections_completed_count, inspections_passed_count, inspections_failed_count, compliance_rate_pct
) values
    ('2026-08-24', 5, 1, 2, 2, 2, 0, 100.0),
    ('2026-08-25', 5, 0, 2, 1, 1, 0, 100.0),
    ('2026-08-26', 5, 2, 3, 3, 2, 1, 66.7),
    ('2026-08-27', 5, 0, 3, 0, 0, 0, 100.0),
    ('2026-08-28', 5, 1, 2, 2, 1, 1, 50.0),
    ('2026-08-29', 4, 0, 2, 1, 1, 0, 100.0),
    ('2026-08-30', 4, 0, 2, 0, 0, 0, 100.0),
    ('2026-08-31', 4, 1, 4, 3, 2, 1, 66.7),
    ('2026-09-01', 5, 0, 3, 1, 1, 0, 100.0),
    ('2026-09-02', 5, 2, 2, 2, 2, 0, 100.0),
    ('2026-09-03', 5, 0, 1, 1, 0, 1, 0.0),
    ('2026-09-04', 5, 1, 2, 2, 2, 0, 100.0),
    ('2026-09-05', 5, 0, 2, 1, 1, 0, 100.0),
    ('2026-09-06', 5, 1, 3, 1, 1, 0, 100.0);
