create table facility (
    id              bigint generated by default as identity primary key,
    name            varchar(200) not null,
    facility_type   varchar(30)  not null,
    address_line1   varchar(200) not null,
    city            varchar(100) not null,
    state           varchar(2)   not null,
    zip             varchar(10)  not null,
    active          boolean      not null default true,
    created_at      timestamp    not null default current_timestamp,
    updated_at      timestamp    not null default current_timestamp
);

create table permit (
    id                  bigint generated by default as identity primary key,
    facility_id         bigint       not null references facility(id) on delete cascade,
    permit_number       varchar(50)  not null unique,
    permit_type         varchar(30)  not null,
    status              varchar(30)  not null,
    description         varchar(1000),
    issued_date         date,
    expiration_date     date,
    created_at          timestamp    not null default current_timestamp,
    updated_at          timestamp    not null default current_timestamp
);

create table inspection (
    id                  bigint generated by default as identity primary key,
    facility_id         bigint       not null references facility(id) on delete cascade,
    permit_id           bigint       references permit(id) on delete set null,
    inspector_name      varchar(150) not null,
    scheduled_date      date         not null,
    completed_date      date,
    outcome             varchar(30)  not null,
    notes               varchar(2000),
    created_at          timestamp    not null default current_timestamp,
    updated_at          timestamp    not null default current_timestamp
);

create index idx_permit_facility on permit(facility_id);
create index idx_permit_status on permit(status);
create index idx_inspection_facility on inspection(facility_id);
create index idx_inspection_permit on inspection(permit_id);
