-- Optional geolocation on facilities. latitude/longitude are the user-facing,
-- editable pair; the location_* columns record everything the capturing
-- device's Geolocation API reported alongside them (accuracy radius, altitude,
-- heading, speed), plus when and how the fix was taken - DEVICE (browser
-- geolocation) or MANUAL (typed/edited by hand, where the extra metadata
-- doesn't apply and is cleared).
alter table facility add column latitude decimal(9,6);
alter table facility add column longitude decimal(9,6);
alter table facility add column location_accuracy_m decimal(10,2);
alter table facility add column location_altitude_m decimal(10,2);
alter table facility add column location_altitude_accuracy_m decimal(10,2);
alter table facility add column location_heading_deg decimal(6,2);
alter table facility add column location_speed_mps decimal(8,2);
alter table facility add column location_captured_at timestamp;
alter table facility add column location_source varchar(10);

-- File/photo attachments on inspections. Bytes live in the row (BLOB) - the
-- right call for a self-contained starter with a 10MB multipart cap; an object
-- store is the production upgrade path and would replace only the data column.
create table inspection_attachment (
    id            bigint generated by default as identity primary key,
    inspection_id bigint        not null references inspection(id) on delete cascade,
    filename      varchar(255)  not null,
    content_type  varchar(100)  not null,
    size_bytes    bigint        not null,
    data          blob          not null,
    uploaded_by   varchar(150),
    uploaded_at   timestamp     not null default current_timestamp
);

create index idx_inspection_attachment_inspection on inspection_attachment(inspection_id);
